
general {
  border_size = 2
  gaps_in = 2
  gaps_out = 0
  resize_on_border = true
   
  col.active_border = $primary $on_primary 90deg
  col.inactive_border = $on_primary

  resize_on_border = true
  layout = dwindle
}

group {
  col.border_active = $primary $on_primary 90deg

	groupbar {
		col.active = $on_primary
  }
}
