windowrule = float 1, match:class ^(pavucontrol)$
windowrule = float 1, match:class ^(blueman-manager)$
windowrule = float 1, match:class ^(nm-connection-editor)$
windowrule = float 1, match:class ^(qalculate-gtk)$
windowrule = workspace 1, match:class ^(kitty)$
windowrule = workspace 4, match:class ^(obsidian)$

#Browser
windowrule = tile 1, match:class ^(firefox)$
windowrule = tile 1, match:class ^(Google-chrome)$
windowrule = workspace 2, match:class ^(firefox)$
windowrule = workspace 3, match:class ^(Google-chrome)$
windowrule = workspace 5, match:class ^(zapzap)$

# Audacious
windowrule = workspace 5 silent, match:class ^([Aa]udacious)$
windowrule = float 1, match:class ^([Aa]udacious)$


# OpenAI ChatGPT floating
windowrule = float 1, match:title (ChatGPT.*)
windowrule = float 1, match:title (.*chat.openai.com.*)
windowrule = size 500 50%, match:title (.*chat.openai.com.*)
windowrule = move 20 70, match:title (.*chat.openai.com.*)

